Repository YAPP-19th/Minning-iOS, pull requests merged in 2021-12, with the labels that each got.

#36 Feature/report empty view
  Minning.xcodeproj/project.pbxproj
  Minning/ViewControllers/Main/Report/Views/ReportEmptyView.swift
Labels: iOS, Feature

#35 [YAPPIOS-177] AddViewController 디자인 수정, iOS15대응
  Minning/ViewControllers/Main/Home/Add/AddDayView.swift
  Minning/ViewControllers/Main/Home/Add/AddViewController.swift
  Minning/ViewControllers/Start/SplashViewController.swift
Labels: Improve, Feature

#38 [YAPPIOS-154] 그룹 상세 페이지 디자인 작업
  Minning.xcodeproj/project.pbxproj
  Minning/ViewControllers/Main/Group/GroupCoordinator.swift
  Minning/ViewControllers/Main/Group/GroupDIContainer.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/GroupDetailViewController.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/GroupDetailViewModel.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupInfoCollectionView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupMyInfoContainerView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupPhotoCell.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupPhotoContainerView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupPhotoPreviewCell.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupPhotoPreviewContainerView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupQuitView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupRuleContainerView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupTitleContainerView.swift
  Minning/ViewControllers/Main/Group/GroupViewController.swift
  Minning/ViewControllers/Main/Group/GroupViewModel.swift
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_empty_photo.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_empty_photo.imageset/Group 455.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_empty_photo.imageset/Group 455@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_empty_photo.imageset/Group 455@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_my_empty_photo.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_my_empty_photo.imageset/Group 458.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_my_empty_photo.imageset/Group 458@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/group_my_empty_photo.imageset/Group 458@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_alarm.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_alarm.imageset/Group 345.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_alarm.imageset/Group 345@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_alarm.imageset/Group 345@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_day.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_day.imageset/Group 473.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_day.imageset/Group 473@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_day.imageset/Group 473@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_term.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_term.imageset/Union.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_term.imageset/Union@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/info_term.imageset/Union@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_bronze.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_bronze.imageset/Group 537.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_bronze.imageset/Group 537@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_bronze.imageset/Group 537@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_gold.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_gold.imageset/Group 535.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_gold.imageset/Group 535@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_gold.imageset/Group 535@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_silver.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_silver.imageset/Group 536.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_silver.imageset/Group 536@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/medal_silver.imageset/Group 536@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_camera.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_camera.imageset/Subtract.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_camera.imageset/Subtract@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_camera.imageset/Subtract@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_exclamation.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_exclamation.imageset/Group 456.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_exclamation.imageset/Group 456@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/rule_exclamation.imageset/Group 456@3x.png
Labels: iOS, Feature

#41 [YAPPIOS-199] 홈탭 상단 뷰 api 적용
  Minning/Model/RoutineModel.swift
  Minning/Network/MinningAPIModel.swift
  Minning/Network/RoutineAPIRequest.swift
  Minning/ViewControllers/Main/Home/HomeViewController.swift
  Minning/ViewControllers/Main/Home/HomeViewModel.swift
  Minning/ViewControllers/Main/Home/Profile/ProfileView.swift
  Minning/ViewControllers/Main/Home/Profile/WeeklyView.swift
  Minning/ViewControllers/Main/Home/Routine/RoutineView.swift
  Minning/ViewControllers/Main/Home/Routine/Views/RoutineCell.swift
Labels: iOS, Feature

#37 [YAPPIOS-195] 카메라 구현
  CommonSystem/CommonSystem.xcodeproj/project.pbxproj
  DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  Minning.xcodeproj/project.pbxproj
  Minning/Info.plist
  Minning/ViewControllers/Main/Group/GroupDetail/JoinGroup/Camera/CameraViewController.swift
  Minning/ViewControllers/Main/Group/GroupDetail/JoinGroup/Camera/PreviewViewController.swift
  Minning/ViewControllers/Main/Group/GroupViewController.swift
  Pods/Pods.xcodeproj/project.pbxproj
  SharedAssets/SharedAssets.xcodeproj/project.pbxproj
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/arrow_back.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/arrow_back.imageset/Vector 78.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/arrow_back.imageset/Vector 78@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/arrow_back.imageset/Vector 78@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/camera_button.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/camera_button.imageset/Ellipse 253.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/camera_button.imageset/Ellipse 253@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/camera_button.imageset/Ellipse 253@3x.png
Labels: iOS, Improve, Feature

#39 [YAPPIOS-167] 월간 리포트 루틴 별 달성률 뷰 작업
  Minning.xcodeproj/project.pbxproj
  Minning/Model/RoutineModel.swift
  Minning/ViewControllers/Main/Report/ReportViewController.swift
  Minning/ViewControllers/Main/Report/Views/RoutineCategoryView.swift
  Minning/ViewControllers/Main/Report/Views/RoutineCompareDetailView.swift
  Minning/ViewControllers/Main/Report/Views/RoutineCompareView.swift
  Minning/ViewControllers/Main/Report/Views/RoutinePercentDetailView.swift
Labels: iOS, Feature

#42 [YAPPIOS-215] 루틴추가 뷰 터치 안되는 에러 해결
  Minning/ViewControllers/Main/Home/Add/AddViewController.swift
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Alamofire/Alamofire.debug.xcconfig
  Pods/Target Support Files/Alamofire/Alamofire.release.xcconfig
Labels: Bug

#40 [YAPPIOS-112] 내 그룹 뷰 만들기
  DesignSystem/DesignSystem/CustomView/PlainButton.swift
  Minning.xcodeproj/project.pbxproj
  Minning/Model/GroupModel.swift
  Minning/ViewControllers/Main/Group/GroupCategoryCell.swift
  Minning/ViewControllers/Main/Group/GroupCoordinator.swift
  Minning/ViewControllers/Main/Group/GroupDIContainer.swift
  Minning/ViewControllers/Main/Group/GroupViewController.swift
  Minning/ViewControllers/Main/Group/GroupViewModel.swift
  Minning/ViewControllers/Main/Group/NewGroup/NewGroupViewController.swift
  Minning/ViewControllers/Main/Group/NewGroup/NewGroupViewModel.swift
  Minning/ViewControllers/Main/Group/Views/GroupCellView.swift
  Minning/ViewControllers/Main/Group/Views/GroupList/GroupListCellViewController.swift
  Minning/ViewControllers/Main/Group/Views/GroupList/GroupListModel.swift
  Minning/ViewControllers/Main/Group/Views/GroupList/GroupListView.swift
  Minning/ViewControllers/Main/Group/Views/GroupListCellViewModel.swift
  Minning/ViewControllers/Main/Group/Views/MyGroup/EndedGroupCellViewController.swift
  Minning/ViewControllers/Main/Group/Views/MyGroup/EndedView.swift
  Minning/ViewControllers/Main/Group/Views/MyGroup/MyGroupCategoryModel.swift
  Minning/ViewControllers/Main/Group/Views/MyGroup/MyGroupCellViewController.swift
  Minning/ViewControllers/Main/Group/Views/MyGroup/OnGoingView.swift
  Minning/ViewControllers/Main/Home/Add/Recommend/RecommendViewController.swift
  Minning/ViewControllers/Main/Home/Add/Recommend/RecommendViewModel.swift
  Pods/Pods.xcodeproj/project.pbxproj
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/categoryWakeUp.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/categoryWakeUp.imageset/image 1454@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/categoryWakeUp.imageset/image 1454@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAlert.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAlert.imageset/Ellipse 241@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAlert.imageset/Ellipse 241@3x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAuthenticated.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAuthenticated.imageset/Group 557.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAuthenticated.imageset/Group 557@2x.png
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/groupAuthenticated.imageset/Group 557@3x.png
Labels: iOS, Feature

#46 Feature/resolve pod install
  DesignSystem/DesignSystem/CustomView/PlainButton.swift
  Minning.xcodeproj/project.pbxproj
  Minning/ViewControllers/Main/Group/GroupCoordinator.swift
  Minning/ViewControllers/Main/Group/GroupDIContainer.swift
  Minning/ViewControllers/Main/Group/GroupViewController.swift
  Minning/ViewControllers/Main/Group/GroupViewModel.swift
  Minning/ViewControllers/Main/Group/NewGroup/NewGroupViewController.swift
  Minning/ViewControllers/Main/Group/NewGroup/NewGroupViewModel.swift
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Alamofire/Alamofire.debug.xcconfig
  Pods/Target Support Files/Alamofire/Alamofire.release.xcconfig
Labels: Bug

#45 [YAPPIOS-199] 홈 루틴 api 적용 중간 PR
  Minning/Model/RoutineModel.swift
  Minning/Network/MinningAPIModel.swift
  Minning/Network/RoutineAPIRequest.swift
  Minning/ViewControllers/Main/Home/Add/AddDayView.swift
  Minning/ViewControllers/Main/Home/Add/AddViewController.swift
  Minning/ViewControllers/Main/Home/Add/AddViewModel.swift
  Minning/ViewControllers/Main/Home/EditOrder/EditOrderViewController.swift
  Minning/ViewControllers/Main/Home/EditOrder/EditOrderViewModel.swift
  Minning/ViewControllers/Main/Home/EditOrder/Views/EditOrderCell.swift
  Minning/ViewControllers/Main/Home/HomeCoordinator.swift
  Minning/ViewControllers/Main/Home/HomeDIContainer.swift
  Minning/ViewControllers/Main/Home/HomeViewModel.swift
  Minning/ViewControllers/Main/Home/Profile/ProfileView.swift
Labels: iOS, Feature

#50 [YAPPIOS-204] 회고, 루틴 api 적용
  Minning/Network/MinningAPIModel.swift
  Minning/Network/MinningRequest.swift
  Minning/Network/RetrospectAPIRequest.swift
  Minning/Network/RoutineAPIRequest.swift
  Minning/ViewControllers/Main/Home/HomeCoordinator.swift
  Minning/ViewControllers/Main/Home/HomeDIContainer.swift
  Minning/ViewControllers/Main/Home/HomeViewController.swift
  Minning/ViewControllers/Main/Home/HomeViewModel.swift
  Minning/ViewControllers/Main/Home/Review/ReviewViewController.swift
  Minning/ViewControllers/Main/Home/Review/ReviewViewModel.swift
  Minning/ViewControllers/Main/Home/Routine/RoutineView.swift
  Minning/ViewControllers/Main/Home/Routine/Views/ReviewCell.swift
  Minning/ViewControllers/Main/Home/Routine/Views/RoutineCell.swift
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/edit_bar_button.imageset/Contents.json
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/edit_bar_button.imageset/Group 349.svg
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/edit_bar_button.imageset/Group 349@2x.svg
  SharedAssets/SharedAssets/Images/ImageSet.xcassets/edit_bar_button.imageset/Group 349@3x.svg
Labels: iOS, Feature

#51 [YAPPIOS-205] 그룹 상세 (그룹 시작 전) api 적용
  CommonSystem/CommonSystem/String+Extensions.swift
  Minning/Network/MinningAPIModel.swift
  Minning/ViewControllers/Main/Group/GroupCoordinator.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/GroupDetailViewController.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/GroupDetailViewModel.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupInfoCollectionView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupRuleContainerView.swift
  Minning/ViewControllers/Main/Group/GroupDetail/GroupDetail/Views/GroupTitleContainerView.swift
Labels: iOS, Feature

#47 [YAPPIOS-168] 루틴 푸시알림 구현
  Minning/AppDelegate.swift
  Minning/Model/NotificationModel.swift
  Pods/Pods.xcodeproj/project.pbxproj
Labels: Bug

#48 [YAPPIOS-227] 루틴추가 뷰 카테고리 중복 선택 불가
  Minning/ViewControllers/Main/Home/Add/AddCategoryView.swift
  Minning/ViewControllers/Main/Home/Add/AddViewController.swift
Labels: iOS, Improve

#52 [YAPPIOS-241] 종료된 그룹 추가 코어데이터 만들기
  EndedGroup+CoreDataClass.swift
  EndedGroup+CoreDataProperties.swift
  Minning.xcodeproj/project.pbxproj
  Minning.xcworkspace/contents.xcworkspacedata
  Minning/AppDelegate.swift
  Minning/CoreData/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
  Minning/CoreData/GroupCoreDataManager.swift
Labels: iOS, Feature
